// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/prbllm/goph-keeper/internal/model"
)

// MockAuthStateStorage is a mock of AuthStateStorage interface.
type MockAuthStateStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAuthStateStorageMockRecorder
}

// MockAuthStateStorageMockRecorder is the mock recorder for MockAuthStateStorage.
type MockAuthStateStorageMockRecorder struct {
	mock *MockAuthStateStorage
}

// NewMockAuthStateStorage creates a new mock instance.
func NewMockAuthStateStorage(ctrl *gomock.Controller) *MockAuthStateStorage {
	mock := &MockAuthStateStorage{ctrl: ctrl}
	mock.recorder = &MockAuthStateStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthStateStorage) EXPECT() *MockAuthStateStorageMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockAuthStateStorage) Load() (*model.AuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*model.AuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockAuthStateStorageMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockAuthStateStorage)(nil).Load))
}

// Save mocks base method.
func (m *MockAuthStateStorage) Save(authState *model.AuthState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", authState)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuthStateStorageMockRecorder) Save(authState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuthStateStorage)(nil).Save), authState)
}

// MockSyncStateStorage is a mock of SyncStateStorage interface.
type MockSyncStateStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateStorageMockRecorder
}

// MockSyncStateStorageMockRecorder is the mock recorder for MockSyncStateStorage.
type MockSyncStateStorageMockRecorder struct {
	mock *MockSyncStateStorage
}

// NewMockSyncStateStorage creates a new mock instance.
func NewMockSyncStateStorage(ctrl *gomock.Controller) *MockSyncStateStorage {
	mock := &MockSyncStateStorage{ctrl: ctrl}
	mock.recorder = &MockSyncStateStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateStorage) EXPECT() *MockSyncStateStorageMockRecorder {
	return m.recorder
}

// LoadSync mocks base method.
func (m *MockSyncStateStorage) LoadSync() (*model.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSync")
	ret0, _ := ret[0].(*model.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSync indicates an expected call of LoadSync.
func (mr *MockSyncStateStorageMockRecorder) LoadSync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSync", reflect.TypeOf((*MockSyncStateStorage)(nil).LoadSync))
}

// SaveSync mocks base method.
func (m *MockSyncStateStorage) SaveSync(syncState *model.SyncState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSync", syncState)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSync indicates an expected call of SaveSync.
func (mr *MockSyncStateStorageMockRecorder) SaveSync(syncState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSync", reflect.TypeOf((*MockSyncStateStorage)(nil).SaveSync), syncState)
}

// MockVaultStorage is a mock of VaultStorage interface.
type MockVaultStorage struct {
	ctrl     *gomock.Controller
	recorder *MockVaultStorageMockRecorder
}

// MockVaultStorageMockRecorder is the mock recorder for MockVaultStorage.
type MockVaultStorageMockRecorder struct {
	mock *MockVaultStorage
}

// NewMockVaultStorage creates a new mock instance.
func NewMockVaultStorage(ctrl *gomock.Controller) *MockVaultStorage {
	mock := &MockVaultStorage{ctrl: ctrl}
	mock.recorder = &MockVaultStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultStorage) EXPECT() *MockVaultStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockVaultStorage) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVaultStorageMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVaultStorage)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockVaultStorage) Get(id string) (*model.Item, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Item)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVaultStorageMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVaultStorage)(nil).Get), id)
}

// List mocks base method.
func (m *MockVaultStorage) List() ([]*model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVaultStorageMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVaultStorage)(nil).List))
}

// Upsert mocks base method.
func (m *MockVaultStorage) Upsert(item *model.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockVaultStorageMockRecorder) Upsert(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockVaultStorage)(nil).Upsert), item)
}

// MockLocalStorage is a mock of LocalStorage interface.
type MockLocalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocalStorageMockRecorder
}

// MockLocalStorageMockRecorder is the mock recorder for MockLocalStorage.
type MockLocalStorageMockRecorder struct {
	mock *MockLocalStorage
}

// NewMockLocalStorage creates a new mock instance.
func NewMockLocalStorage(ctrl *gomock.Controller) *MockLocalStorage {
	mock := &MockLocalStorage{ctrl: ctrl}
	mock.recorder = &MockLocalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalStorage) EXPECT() *MockLocalStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLocalStorage) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLocalStorageMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLocalStorage)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockLocalStorage) Get(id string) (*model.Item, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Item)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLocalStorageMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLocalStorage)(nil).Get), id)
}

// List mocks base method.
func (m *MockLocalStorage) List() ([]*model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLocalStorageMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLocalStorage)(nil).List))
}

// Load mocks base method.
func (m *MockLocalStorage) Load() (*model.AuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*model.AuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockLocalStorageMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockLocalStorage)(nil).Load))
}

// LoadSync mocks base method.
func (m *MockLocalStorage) LoadSync() (*model.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSync")
	ret0, _ := ret[0].(*model.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSync indicates an expected call of LoadSync.
func (mr *MockLocalStorageMockRecorder) LoadSync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSync", reflect.TypeOf((*MockLocalStorage)(nil).LoadSync))
}

// Save mocks base method.
func (m *MockLocalStorage) Save(authState *model.AuthState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", authState)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLocalStorageMockRecorder) Save(authState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLocalStorage)(nil).Save), authState)
}

// SaveSync mocks base method.
func (m *MockLocalStorage) SaveSync(syncState *model.SyncState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSync", syncState)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSync indicates an expected call of SaveSync.
func (mr *MockLocalStorageMockRecorder) SaveSync(syncState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSync", reflect.TypeOf((*MockLocalStorage)(nil).SaveSync), syncState)
}

// Upsert mocks base method.
func (m *MockLocalStorage) Upsert(item *model.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockLocalStorageMockRecorder) Upsert(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockLocalStorage)(nil).Upsert), item)
}
