// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/api (interfaces: SyncServiceClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	api "github.com/prbllm/goph-keeper/api"
	grpc "google.golang.org/grpc"
)

// MockSyncServiceClient is a mock of SyncServiceClient interface.
type MockSyncServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSyncServiceClientMockRecorder
}

// MockSyncServiceClientMockRecorder is the mock recorder for MockSyncServiceClient.
type MockSyncServiceClientMockRecorder struct {
	mock *MockSyncServiceClient
}

// NewMockSyncServiceClient creates a new mock instance.
func NewMockSyncServiceClient(ctrl *gomock.Controller) *MockSyncServiceClient {
	mock := &MockSyncServiceClient{ctrl: ctrl}
	mock.recorder = &MockSyncServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncServiceClient) EXPECT() *MockSyncServiceClientMockRecorder {
	return m.recorder
}

// PullChanges mocks base method.
func (m *MockSyncServiceClient) PullChanges(arg0 context.Context, arg1 *api.PullChangesRequest, arg2 ...grpc.CallOption) (*api.PullChangesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PullChanges", varargs...)
	ret0, _ := ret[0].(*api.PullChangesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullChanges indicates an expected call of PullChanges.
func (mr *MockSyncServiceClientMockRecorder) PullChanges(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullChanges", reflect.TypeOf((*MockSyncServiceClient)(nil).PullChanges), varargs...)
}

// PushChanges mocks base method.
func (m *MockSyncServiceClient) PushChanges(arg0 context.Context, arg1 *api.PushChangesRequest, arg2 ...grpc.CallOption) (*api.PushChangesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PushChanges", varargs...)
	ret0, _ := ret[0].(*api.PushChangesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushChanges indicates an expected call of PushChanges.
func (mr *MockSyncServiceClientMockRecorder) PushChanges(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushChanges", reflect.TypeOf((*MockSyncServiceClient)(nil).PushChanges), varargs...)
}

// Sync mocks base method.
func (m *MockSyncServiceClient) Sync(arg0 context.Context, arg1 *api.SyncRequest, arg2 ...grpc.CallOption) (*api.SyncResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sync", varargs...)
	ret0, _ := ret[0].(*api.SyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockSyncServiceClientMockRecorder) Sync(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockSyncServiceClient)(nil).Sync), varargs...)
}
