// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	api "github.com/prbllm/goph-keeper/api"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AuthClient mocks base method.
func (m *MockClient) AuthClient() api.AuthServiceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthClient")
	ret0, _ := ret[0].(api.AuthServiceClient)
	return ret0
}

// AuthClient indicates an expected call of AuthClient.
func (mr *MockClientMockRecorder) AuthClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthClient", reflect.TypeOf((*MockClient)(nil).AuthClient))
}

// BlobClient mocks base method.
func (m *MockClient) BlobClient() api.BlobServiceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobClient")
	ret0, _ := ret[0].(api.BlobServiceClient)
	return ret0
}

// BlobClient indicates an expected call of BlobClient.
func (mr *MockClientMockRecorder) BlobClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobClient", reflect.TypeOf((*MockClient)(nil).BlobClient))
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// SyncClient mocks base method.
func (m *MockClient) SyncClient() api.SyncServiceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncClient")
	ret0, _ := ret[0].(api.SyncServiceClient)
	return ret0
}

// SyncClient indicates an expected call of SyncClient.
func (mr *MockClientMockRecorder) SyncClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncClient", reflect.TypeOf((*MockClient)(nil).SyncClient))
}

// VaultClient mocks base method.
func (m *MockClient) VaultClient() api.VaultServiceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VaultClient")
	ret0, _ := ret[0].(api.VaultServiceClient)
	return ret0
}

// VaultClient indicates an expected call of VaultClient.
func (mr *MockClientMockRecorder) VaultClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VaultClient", reflect.TypeOf((*MockClient)(nil).VaultClient))
}
