// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/internal/server/vault (interfaces: Repository,RevisionLogRepository,ProcessedOperationsRepository,Engine)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/mock_vault.go -package=mocks . Repository,RevisionLogRepository,ProcessedOperationsRepository,Engine
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	vault "github.com/prbllm/goph-keeper/internal/server/vault"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MockRepository) CreateItem(ctx context.Context, it *vault.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, it)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockRepositoryMockRecorder) CreateItem(ctx, it any) *MockRepositoryCreateItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockRepository)(nil).CreateItem), ctx, it)
	return &MockRepositoryCreateItemCall{Call: call}
}

// MockRepositoryCreateItemCall wrap *gomock.Call
type MockRepositoryCreateItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateItemCall) Return(arg0 error) *MockRepositoryCreateItemCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateItemCall) Do(f func(context.Context, *vault.Item) error) *MockRepositoryCreateItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateItemCall) DoAndReturn(f func(context.Context, *vault.Item) error) *MockRepositoryCreateItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteItem mocks base method.
func (m *MockRepository) DeleteItem(ctx context.Context, userID, itemID string, expectedVersion uint64, deletedAt time.Time) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, userID, itemID, expectedVersion, deletedAt)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockRepositoryMockRecorder) DeleteItem(ctx, userID, itemID, expectedVersion, deletedAt any) *MockRepositoryDeleteItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockRepository)(nil).DeleteItem), ctx, userID, itemID, expectedVersion, deletedAt)
	return &MockRepositoryDeleteItemCall{Call: call}
}

// MockRepositoryDeleteItemCall wrap *gomock.Call
type MockRepositoryDeleteItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteItemCall) Return(arg0 uint64, arg1 error) *MockRepositoryDeleteItemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteItemCall) Do(f func(context.Context, string, string, uint64, time.Time) (uint64, error)) *MockRepositoryDeleteItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteItemCall) DoAndReturn(f func(context.Context, string, string, uint64, time.Time) (uint64, error)) *MockRepositoryDeleteItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetItem mocks base method.
func (m *MockRepository) GetItem(ctx context.Context, userID, itemID string) (*vault.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, userID, itemID)
	ret0, _ := ret[0].(*vault.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockRepositoryMockRecorder) GetItem(ctx, userID, itemID any) *MockRepositoryGetItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockRepository)(nil).GetItem), ctx, userID, itemID)
	return &MockRepositoryGetItemCall{Call: call}
}

// MockRepositoryGetItemCall wrap *gomock.Call
type MockRepositoryGetItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetItemCall) Return(arg0 *vault.Item, arg1 error) *MockRepositoryGetItemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetItemCall) Do(f func(context.Context, string, string) (*vault.Item, error)) *MockRepositoryGetItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetItemCall) DoAndReturn(f func(context.Context, string, string) (*vault.Item, error)) *MockRepositoryGetItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListItems mocks base method.
func (m *MockRepository) ListItems(ctx context.Context, userID string, includeDeleted bool, limit int32, pageToken string) ([]*vault.Item, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, userID, includeDeleted, limit, pageToken)
	ret0, _ := ret[0].([]*vault.Item)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListItems indicates an expected call of ListItems.
func (mr *MockRepositoryMockRecorder) ListItems(ctx, userID, includeDeleted, limit, pageToken any) *MockRepositoryListItemsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockRepository)(nil).ListItems), ctx, userID, includeDeleted, limit, pageToken)
	return &MockRepositoryListItemsCall{Call: call}
}

// MockRepositoryListItemsCall wrap *gomock.Call
type MockRepositoryListItemsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListItemsCall) Return(arg0 []*vault.Item, arg1 string, arg2 error) *MockRepositoryListItemsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListItemsCall) Do(f func(context.Context, string, bool, int32, string) ([]*vault.Item, string, error)) *MockRepositoryListItemsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListItemsCall) DoAndReturn(f func(context.Context, string, bool, int32, string) ([]*vault.Item, string, error)) *MockRepositoryListItemsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateItem mocks base method.
func (m *MockRepository) UpdateItem(ctx context.Context, it *vault.Item, expectedVersion uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, it, expectedVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockRepositoryMockRecorder) UpdateItem(ctx, it, expectedVersion any) *MockRepositoryUpdateItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockRepository)(nil).UpdateItem), ctx, it, expectedVersion)
	return &MockRepositoryUpdateItemCall{Call: call}
}

// MockRepositoryUpdateItemCall wrap *gomock.Call
type MockRepositoryUpdateItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateItemCall) Return(arg0 error) *MockRepositoryUpdateItemCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateItemCall) Do(f func(context.Context, *vault.Item, uint64) error) *MockRepositoryUpdateItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateItemCall) DoAndReturn(f func(context.Context, *vault.Item, uint64) error) *MockRepositoryUpdateItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRevisionLogRepository is a mock of RevisionLogRepository interface.
type MockRevisionLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRevisionLogRepositoryMockRecorder
	isgomock struct{}
}

// MockRevisionLogRepositoryMockRecorder is the mock recorder for MockRevisionLogRepository.
type MockRevisionLogRepositoryMockRecorder struct {
	mock *MockRevisionLogRepository
}

// NewMockRevisionLogRepository creates a new mock instance.
func NewMockRevisionLogRepository(ctrl *gomock.Controller) *MockRevisionLogRepository {
	mock := &MockRevisionLogRepository{ctrl: ctrl}
	mock.recorder = &MockRevisionLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevisionLogRepository) EXPECT() *MockRevisionLogRepositoryMockRecorder {
	return m.recorder
}

// AppendRevision mocks base method.
func (m *MockRevisionLogRepository) AppendRevision(ctx context.Context, entry *vault.RevisionLogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendRevision", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendRevision indicates an expected call of AppendRevision.
func (mr *MockRevisionLogRepositoryMockRecorder) AppendRevision(ctx, entry any) *MockRevisionLogRepositoryAppendRevisionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRevision", reflect.TypeOf((*MockRevisionLogRepository)(nil).AppendRevision), ctx, entry)
	return &MockRevisionLogRepositoryAppendRevisionCall{Call: call}
}

// MockRevisionLogRepositoryAppendRevisionCall wrap *gomock.Call
type MockRevisionLogRepositoryAppendRevisionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRevisionLogRepositoryAppendRevisionCall) Return(arg0 error) *MockRevisionLogRepositoryAppendRevisionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRevisionLogRepositoryAppendRevisionCall) Do(f func(context.Context, *vault.RevisionLogEntry) error) *MockRevisionLogRepositoryAppendRevisionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRevisionLogRepositoryAppendRevisionCall) DoAndReturn(f func(context.Context, *vault.RevisionLogEntry) error) *MockRevisionLogRepositoryAppendRevisionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProcessedOperationsRepository is a mock of ProcessedOperationsRepository interface.
type MockProcessedOperationsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProcessedOperationsRepositoryMockRecorder
	isgomock struct{}
}

// MockProcessedOperationsRepositoryMockRecorder is the mock recorder for MockProcessedOperationsRepository.
type MockProcessedOperationsRepositoryMockRecorder struct {
	mock *MockProcessedOperationsRepository
}

// NewMockProcessedOperationsRepository creates a new mock instance.
func NewMockProcessedOperationsRepository(ctrl *gomock.Controller) *MockProcessedOperationsRepository {
	mock := &MockProcessedOperationsRepository{ctrl: ctrl}
	mock.recorder = &MockProcessedOperationsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessedOperationsRepository) EXPECT() *MockProcessedOperationsRepositoryMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockProcessedOperationsRepository) Lookup(ctx context.Context, userID, operationID string) (*vault.ProcessedOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, userID, operationID)
	ret0, _ := ret[0].(*vault.ProcessedOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockProcessedOperationsRepositoryMockRecorder) Lookup(ctx, userID, operationID any) *MockProcessedOperationsRepositoryLookupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockProcessedOperationsRepository)(nil).Lookup), ctx, userID, operationID)
	return &MockProcessedOperationsRepositoryLookupCall{Call: call}
}

// MockProcessedOperationsRepositoryLookupCall wrap *gomock.Call
type MockProcessedOperationsRepositoryLookupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProcessedOperationsRepositoryLookupCall) Return(arg0 *vault.ProcessedOperation, arg1 error) *MockProcessedOperationsRepositoryLookupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProcessedOperationsRepositoryLookupCall) Do(f func(context.Context, string, string) (*vault.ProcessedOperation, error)) *MockProcessedOperationsRepositoryLookupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProcessedOperationsRepositoryLookupCall) DoAndReturn(f func(context.Context, string, string) (*vault.ProcessedOperation, error)) *MockProcessedOperationsRepositoryLookupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkProcessed mocks base method.
func (m *MockProcessedOperationsRepository) MarkProcessed(ctx context.Context, userID, operationID, itemID string, revisionID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, userID, operationID, itemID, revisionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockProcessedOperationsRepositoryMockRecorder) MarkProcessed(ctx, userID, operationID, itemID, revisionID any) *MockProcessedOperationsRepositoryMarkProcessedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockProcessedOperationsRepository)(nil).MarkProcessed), ctx, userID, operationID, itemID, revisionID)
	return &MockProcessedOperationsRepositoryMarkProcessedCall{Call: call}
}

// MockProcessedOperationsRepositoryMarkProcessedCall wrap *gomock.Call
type MockProcessedOperationsRepositoryMarkProcessedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProcessedOperationsRepositoryMarkProcessedCall) Return(arg0 error) *MockProcessedOperationsRepositoryMarkProcessedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProcessedOperationsRepositoryMarkProcessedCall) Do(f func(context.Context, string, string, string, uint64) error) *MockProcessedOperationsRepositoryMarkProcessedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProcessedOperationsRepositoryMarkProcessedCall) DoAndReturn(f func(context.Context, string, string, string, uint64) error) *MockProcessedOperationsRepositoryMarkProcessedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
	isgomock struct{}
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEngine) Create(ctx context.Context, userID, operationID string, in vault.CreateInput) (*vault.CreateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, operationID, in)
	ret0, _ := ret[0].(*vault.CreateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEngineMockRecorder) Create(ctx, userID, operationID, in any) *MockEngineCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEngine)(nil).Create), ctx, userID, operationID, in)
	return &MockEngineCreateCall{Call: call}
}

// MockEngineCreateCall wrap *gomock.Call
type MockEngineCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineCreateCall) Return(arg0 *vault.CreateOutput, arg1 error) *MockEngineCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineCreateCall) Do(f func(context.Context, string, string, vault.CreateInput) (*vault.CreateOutput, error)) *MockEngineCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineCreateCall) DoAndReturn(f func(context.Context, string, string, vault.CreateInput) (*vault.CreateOutput, error)) *MockEngineCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockEngine) Delete(ctx context.Context, userID, operationID, itemID string, expectedVersion uint64) (*vault.DeleteOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, operationID, itemID, expectedVersion)
	ret0, _ := ret[0].(*vault.DeleteOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockEngineMockRecorder) Delete(ctx, userID, operationID, itemID, expectedVersion any) *MockEngineDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEngine)(nil).Delete), ctx, userID, operationID, itemID, expectedVersion)
	return &MockEngineDeleteCall{Call: call}
}

// MockEngineDeleteCall wrap *gomock.Call
type MockEngineDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineDeleteCall) Return(arg0 *vault.DeleteOutput, arg1 error) *MockEngineDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineDeleteCall) Do(f func(context.Context, string, string, string, uint64) (*vault.DeleteOutput, error)) *MockEngineDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineDeleteCall) DoAndReturn(f func(context.Context, string, string, string, uint64) (*vault.DeleteOutput, error)) *MockEngineDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockEngine) Get(ctx context.Context, userID, itemID string) (*vault.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, itemID)
	ret0, _ := ret[0].(*vault.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEngineMockRecorder) Get(ctx, userID, itemID any) *MockEngineGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEngine)(nil).Get), ctx, userID, itemID)
	return &MockEngineGetCall{Call: call}
}

// MockEngineGetCall wrap *gomock.Call
type MockEngineGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineGetCall) Return(arg0 *vault.Item, arg1 error) *MockEngineGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineGetCall) Do(f func(context.Context, string, string) (*vault.Item, error)) *MockEngineGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineGetCall) DoAndReturn(f func(context.Context, string, string) (*vault.Item, error)) *MockEngineGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockEngine) List(ctx context.Context, userID string, includeDeleted bool, pageSize int32, pageToken string) ([]*vault.Item, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, includeDeleted, pageSize, pageToken)
	ret0, _ := ret[0].([]*vault.Item)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockEngineMockRecorder) List(ctx, userID, includeDeleted, pageSize, pageToken any) *MockEngineListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEngine)(nil).List), ctx, userID, includeDeleted, pageSize, pageToken)
	return &MockEngineListCall{Call: call}
}

// MockEngineListCall wrap *gomock.Call
type MockEngineListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineListCall) Return(arg0 []*vault.Item, arg1 string, arg2 error) *MockEngineListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineListCall) Do(f func(context.Context, string, bool, int32, string) ([]*vault.Item, string, error)) *MockEngineListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineListCall) DoAndReturn(f func(context.Context, string, bool, int32, string) ([]*vault.Item, string, error)) *MockEngineListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockEngine) Update(ctx context.Context, userID, operationID, itemID string, expectedVersion uint64, in vault.UpdateInput) (*vault.UpdateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, operationID, itemID, expectedVersion, in)
	ret0, _ := ret[0].(*vault.UpdateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEngineMockRecorder) Update(ctx, userID, operationID, itemID, expectedVersion, in any) *MockEngineUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEngine)(nil).Update), ctx, userID, operationID, itemID, expectedVersion, in)
	return &MockEngineUpdateCall{Call: call}
}

// MockEngineUpdateCall wrap *gomock.Call
type MockEngineUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineUpdateCall) Return(arg0 *vault.UpdateOutput, arg1 error) *MockEngineUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineUpdateCall) Do(f func(context.Context, string, string, string, uint64, vault.UpdateInput) (*vault.UpdateOutput, error)) *MockEngineUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineUpdateCall) DoAndReturn(f func(context.Context, string, string, string, uint64, vault.UpdateInput) (*vault.UpdateOutput, error)) *MockEngineUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
