// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/internal/server/auth (interfaces: UserRepository,AuthTx,SessionRepository,PasswordHasher,TokenIssuer)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/mock_auth.go -package=mocks . UserRepository,AuthTx,SessionRepository,PasswordHasher,TokenIssuer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	auth "github.com/prbllm/goph-keeper/internal/server/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByLogin mocks base method.
func (m *MockUserRepository) GetByLogin(ctx context.Context, login string) (*auth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(*auth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockUserRepositoryMockRecorder) GetByLogin(ctx, login any) *MockUserRepositoryGetByLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockUserRepository)(nil).GetByLogin), ctx, login)
	return &MockUserRepositoryGetByLoginCall{Call: call}
}

// MockUserRepositoryGetByLoginCall wrap *gomock.Call
type MockUserRepositoryGetByLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetByLoginCall) Return(arg0 *auth.User, arg1 error) *MockUserRepositoryGetByLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetByLoginCall) Do(f func(context.Context, string) (*auth.User, error)) *MockUserRepositoryGetByLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetByLoginCall) DoAndReturn(f func(context.Context, string) (*auth.User, error)) *MockUserRepositoryGetByLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAuthTx is a mock of AuthTx interface.
type MockAuthTx struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTxMockRecorder
	isgomock struct{}
}

// MockAuthTxMockRecorder is the mock recorder for MockAuthTx.
type MockAuthTxMockRecorder struct {
	mock *MockAuthTx
}

// NewMockAuthTx creates a new mock instance.
func NewMockAuthTx(ctrl *gomock.Controller) *MockAuthTx {
	mock := &MockAuthTx{ctrl: ctrl}
	mock.recorder = &MockAuthTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTx) EXPECT() *MockAuthTxMockRecorder {
	return m.recorder
}

// LoginWithDeviceAndSession mocks base method.
func (m *MockAuthTx) LoginWithDeviceAndSession(ctx context.Context, device *auth.Device, session *auth.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithDeviceAndSession", ctx, device, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoginWithDeviceAndSession indicates an expected call of LoginWithDeviceAndSession.
func (mr *MockAuthTxMockRecorder) LoginWithDeviceAndSession(ctx, device, session any) *MockAuthTxLoginWithDeviceAndSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithDeviceAndSession", reflect.TypeOf((*MockAuthTx)(nil).LoginWithDeviceAndSession), ctx, device, session)
	return &MockAuthTxLoginWithDeviceAndSessionCall{Call: call}
}

// MockAuthTxLoginWithDeviceAndSessionCall wrap *gomock.Call
type MockAuthTxLoginWithDeviceAndSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthTxLoginWithDeviceAndSessionCall) Return(arg0 error) *MockAuthTxLoginWithDeviceAndSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthTxLoginWithDeviceAndSessionCall) Do(f func(context.Context, *auth.Device, *auth.Session) error) *MockAuthTxLoginWithDeviceAndSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthTxLoginWithDeviceAndSessionCall) DoAndReturn(f func(context.Context, *auth.Device, *auth.Session) error) *MockAuthTxLoginWithDeviceAndSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterWithSession mocks base method.
func (m *MockAuthTx) RegisterWithSession(ctx context.Context, user *auth.User, device *auth.Device, session *auth.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterWithSession", ctx, user, device, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterWithSession indicates an expected call of RegisterWithSession.
func (mr *MockAuthTxMockRecorder) RegisterWithSession(ctx, user, device, session any) *MockAuthTxRegisterWithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterWithSession", reflect.TypeOf((*MockAuthTx)(nil).RegisterWithSession), ctx, user, device, session)
	return &MockAuthTxRegisterWithSessionCall{Call: call}
}

// MockAuthTxRegisterWithSessionCall wrap *gomock.Call
type MockAuthTxRegisterWithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthTxRegisterWithSessionCall) Return(arg0 error) *MockAuthTxRegisterWithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthTxRegisterWithSessionCall) Do(f func(context.Context, *auth.User, *auth.Device, *auth.Session) error) *MockAuthTxRegisterWithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthTxRegisterWithSessionCall) DoAndReturn(f func(context.Context, *auth.User, *auth.Device, *auth.Session) error) *MockAuthTxRegisterWithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// RevokeByHash mocks base method.
func (m *MockSessionRepository) RevokeByHash(ctx context.Context, tokenHash []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByHash indicates an expected call of RevokeByHash.
func (mr *MockSessionRepositoryMockRecorder) RevokeByHash(ctx, tokenHash any) *MockSessionRepositoryRevokeByHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByHash", reflect.TypeOf((*MockSessionRepository)(nil).RevokeByHash), ctx, tokenHash)
	return &MockSessionRepositoryRevokeByHashCall{Call: call}
}

// MockSessionRepositoryRevokeByHashCall wrap *gomock.Call
type MockSessionRepositoryRevokeByHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryRevokeByHashCall) Return(arg0 error) *MockSessionRepositoryRevokeByHashCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryRevokeByHashCall) Do(f func(context.Context, []byte) error) *MockSessionRepositoryRevokeByHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryRevokeByHashCall) DoAndReturn(f func(context.Context, []byte) error) *MockSessionRepositoryRevokeByHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RotateRefresh mocks base method.
func (m *MockSessionRepository) RotateRefresh(ctx context.Context, oldTokenHash []byte, deviceID string, now time.Time, newSession *auth.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefresh", ctx, oldTokenHash, deviceID, now, newSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateRefresh indicates an expected call of RotateRefresh.
func (mr *MockSessionRepositoryMockRecorder) RotateRefresh(ctx, oldTokenHash, deviceID, now, newSession any) *MockSessionRepositoryRotateRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefresh", reflect.TypeOf((*MockSessionRepository)(nil).RotateRefresh), ctx, oldTokenHash, deviceID, now, newSession)
	return &MockSessionRepositoryRotateRefreshCall{Call: call}
}

// MockSessionRepositoryRotateRefreshCall wrap *gomock.Call
type MockSessionRepositoryRotateRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryRotateRefreshCall) Return(arg0 error) *MockSessionRepositoryRotateRefreshCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryRotateRefreshCall) Do(f func(context.Context, []byte, string, time.Time, *auth.Session) error) *MockSessionRepositoryRotateRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryRotateRefreshCall) DoAndReturn(f func(context.Context, []byte, string, time.Time, *auth.Session) error) *MockSessionRepositoryRotateRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
	isgomock struct{}
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockPasswordHasher) Compare(hash []byte, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hash, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockPasswordHasherMockRecorder) Compare(hash, password any) *MockPasswordHasherCompareCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockPasswordHasher)(nil).Compare), hash, password)
	return &MockPasswordHasherCompareCall{Call: call}
}

// MockPasswordHasherCompareCall wrap *gomock.Call
type MockPasswordHasherCompareCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasswordHasherCompareCall) Return(arg0 error) *MockPasswordHasherCompareCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasswordHasherCompareCall) Do(f func([]byte, string) error) *MockPasswordHasherCompareCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasswordHasherCompareCall) DoAndReturn(f func([]byte, string) error) *MockPasswordHasherCompareCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Hash mocks base method.
func (m *MockPasswordHasher) Hash(password string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordHasherMockRecorder) Hash(password any) *MockPasswordHasherHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordHasher)(nil).Hash), password)
	return &MockPasswordHasherHashCall{Call: call}
}

// MockPasswordHasherHashCall wrap *gomock.Call
type MockPasswordHasherHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasswordHasherHashCall) Return(arg0 []byte, arg1 error) *MockPasswordHasherHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasswordHasherHashCall) Do(f func(string) ([]byte, error)) *MockPasswordHasherHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasswordHasherHashCall) DoAndReturn(f func(string) ([]byte, error)) *MockPasswordHasherHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// IssueAccessToken mocks base method.
func (m *MockTokenIssuer) IssueAccessToken(claims auth.AccessTokenClaims, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessToken", claims, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessToken indicates an expected call of IssueAccessToken.
func (mr *MockTokenIssuerMockRecorder) IssueAccessToken(claims, ttl any) *MockTokenIssuerIssueAccessTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessToken", reflect.TypeOf((*MockTokenIssuer)(nil).IssueAccessToken), claims, ttl)
	return &MockTokenIssuerIssueAccessTokenCall{Call: call}
}

// MockTokenIssuerIssueAccessTokenCall wrap *gomock.Call
type MockTokenIssuerIssueAccessTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenIssuerIssueAccessTokenCall) Return(arg0 string, arg1 error) *MockTokenIssuerIssueAccessTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenIssuerIssueAccessTokenCall) Do(f func(auth.AccessTokenClaims, time.Duration) (string, error)) *MockTokenIssuerIssueAccessTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenIssuerIssueAccessTokenCall) DoAndReturn(f func(auth.AccessTokenClaims, time.Duration) (string, error)) *MockTokenIssuerIssueAccessTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
