// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/internal/server/storage/s3minio (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -typed -destination=../mocks/mock_s3minio.go -package=mocks . Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	minio "github.com/minio/minio-go/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BucketExists mocks base method.
func (m *MockClient) BucketExists(ctx context.Context, bucketName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketExists", ctx, bucketName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketExists indicates an expected call of BucketExists.
func (mr *MockClientMockRecorder) BucketExists(ctx, bucketName any) *MockClientBucketExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketExists", reflect.TypeOf((*MockClient)(nil).BucketExists), ctx, bucketName)
	return &MockClientBucketExistsCall{Call: call}
}

// MockClientBucketExistsCall wrap *gomock.Call
type MockClientBucketExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientBucketExistsCall) Return(arg0 bool, arg1 error) *MockClientBucketExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientBucketExistsCall) Do(f func(context.Context, string) (bool, error)) *MockClientBucketExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientBucketExistsCall) DoAndReturn(f func(context.Context, string) (bool, error)) *MockClientBucketExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetObject mocks base method.
func (m *MockClient) GetObject(ctx context.Context, bucketName, objectName string, opts minio.GetObjectOptions) (*minio.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(*minio.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockClientMockRecorder) GetObject(ctx, bucketName, objectName, opts any) *MockClientGetObjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockClient)(nil).GetObject), ctx, bucketName, objectName, opts)
	return &MockClientGetObjectCall{Call: call}
}

// MockClientGetObjectCall wrap *gomock.Call
type MockClientGetObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetObjectCall) Return(arg0 *minio.Object, arg1 error) *MockClientGetObjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetObjectCall) Do(f func(context.Context, string, string, minio.GetObjectOptions) (*minio.Object, error)) *MockClientGetObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetObjectCall) DoAndReturn(f func(context.Context, string, string, minio.GetObjectOptions) (*minio.Object, error)) *MockClientGetObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListBuckets mocks base method.
func (m *MockClient) ListBuckets(ctx context.Context) ([]minio.BucketInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuckets", ctx)
	ret0, _ := ret[0].([]minio.BucketInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuckets indicates an expected call of ListBuckets.
func (mr *MockClientMockRecorder) ListBuckets(ctx any) *MockClientListBucketsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuckets", reflect.TypeOf((*MockClient)(nil).ListBuckets), ctx)
	return &MockClientListBucketsCall{Call: call}
}

// MockClientListBucketsCall wrap *gomock.Call
type MockClientListBucketsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientListBucketsCall) Return(arg0 []minio.BucketInfo, arg1 error) *MockClientListBucketsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientListBucketsCall) Do(f func(context.Context) ([]minio.BucketInfo, error)) *MockClientListBucketsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientListBucketsCall) DoAndReturn(f func(context.Context) ([]minio.BucketInfo, error)) *MockClientListBucketsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MakeBucket mocks base method.
func (m *MockClient) MakeBucket(ctx context.Context, bucketName string, opts minio.MakeBucketOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBucket", ctx, bucketName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeBucket indicates an expected call of MakeBucket.
func (mr *MockClientMockRecorder) MakeBucket(ctx, bucketName, opts any) *MockClientMakeBucketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBucket", reflect.TypeOf((*MockClient)(nil).MakeBucket), ctx, bucketName, opts)
	return &MockClientMakeBucketCall{Call: call}
}

// MockClientMakeBucketCall wrap *gomock.Call
type MockClientMakeBucketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientMakeBucketCall) Return(arg0 error) *MockClientMakeBucketCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientMakeBucketCall) Do(f func(context.Context, string, minio.MakeBucketOptions) error) *MockClientMakeBucketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientMakeBucketCall) DoAndReturn(f func(context.Context, string, minio.MakeBucketOptions) error) *MockClientMakeBucketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutObject mocks base method.
func (m *MockClient) PutObject(ctx context.Context, bucketName, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (minio.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucketName, objectName, reader, objectSize, opts)
	ret0, _ := ret[0].(minio.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockClientMockRecorder) PutObject(ctx, bucketName, objectName, reader, objectSize, opts any) *MockClientPutObjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockClient)(nil).PutObject), ctx, bucketName, objectName, reader, objectSize, opts)
	return &MockClientPutObjectCall{Call: call}
}

// MockClientPutObjectCall wrap *gomock.Call
type MockClientPutObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientPutObjectCall) Return(arg0 minio.UploadInfo, arg1 error) *MockClientPutObjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientPutObjectCall) Do(f func(context.Context, string, string, io.Reader, int64, minio.PutObjectOptions) (minio.UploadInfo, error)) *MockClientPutObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientPutObjectCall) DoAndReturn(f func(context.Context, string, string, io.Reader, int64, minio.PutObjectOptions) (minio.UploadInfo, error)) *MockClientPutObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveObject mocks base method.
func (m *MockClient) RemoveObject(ctx context.Context, bucketName, objectName string, opts minio.RemoveObjectOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObject indicates an expected call of RemoveObject.
func (mr *MockClientMockRecorder) RemoveObject(ctx, bucketName, objectName, opts any) *MockClientRemoveObjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObject", reflect.TypeOf((*MockClient)(nil).RemoveObject), ctx, bucketName, objectName, opts)
	return &MockClientRemoveObjectCall{Call: call}
}

// MockClientRemoveObjectCall wrap *gomock.Call
type MockClientRemoveObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientRemoveObjectCall) Return(arg0 error) *MockClientRemoveObjectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientRemoveObjectCall) Do(f func(context.Context, string, string, minio.RemoveObjectOptions) error) *MockClientRemoveObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientRemoveObjectCall) DoAndReturn(f func(context.Context, string, string, minio.RemoveObjectOptions) error) *MockClientRemoveObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StatObject mocks base method.
func (m *MockClient) StatObject(ctx context.Context, bucketName, objectName string, opts minio.StatObjectOptions) (minio.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(minio.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatObject indicates an expected call of StatObject.
func (mr *MockClientMockRecorder) StatObject(ctx, bucketName, objectName, opts any) *MockClientStatObjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatObject", reflect.TypeOf((*MockClient)(nil).StatObject), ctx, bucketName, objectName, opts)
	return &MockClientStatObjectCall{Call: call}
}

// MockClientStatObjectCall wrap *gomock.Call
type MockClientStatObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientStatObjectCall) Return(arg0 minio.ObjectInfo, arg1 error) *MockClientStatObjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientStatObjectCall) Do(f func(context.Context, string, string, minio.StatObjectOptions) (minio.ObjectInfo, error)) *MockClientStatObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientStatObjectCall) DoAndReturn(f func(context.Context, string, string, minio.StatObjectOptions) (minio.ObjectInfo, error)) *MockClientStatObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
