// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/internal/server/storage/postgres (interfaces: Pool,Connector)
//
// Generated by this command:
//
//	mockgen -typed -destination=../mocks/mock_postgres.go -package=mocks . Pool,Connector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	postgres "github.com/prbllm/goph-keeper/internal/server/storage/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockPool is a mock of Pool interface.
type MockPool struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMockRecorder
	isgomock struct{}
}

// MockPoolMockRecorder is the mock recorder for MockPool.
type MockPoolMockRecorder struct {
	mock *MockPool
}

// NewMockPool creates a new mock instance.
func NewMockPool(ctrl *gomock.Controller) *MockPool {
	mock := &MockPool{ctrl: ctrl}
	mock.recorder = &MockPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPool) EXPECT() *MockPoolMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockPool) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockPoolMockRecorder) BeginTx(ctx, opts any) *MockPoolBeginTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockPool)(nil).BeginTx), ctx, opts)
	return &MockPoolBeginTxCall{Call: call}
}

// MockPoolBeginTxCall wrap *gomock.Call
type MockPoolBeginTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoolBeginTxCall) Return(arg0 *sql.Tx, arg1 error) *MockPoolBeginTxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPoolBeginTxCall) Do(f func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockPoolBeginTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoolBeginTxCall) DoAndReturn(f func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockPoolBeginTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockPool) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPoolMockRecorder) Close() *MockPoolCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPool)(nil).Close))
	return &MockPoolCloseCall{Call: call}
}

// MockPoolCloseCall wrap *gomock.Call
type MockPoolCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoolCloseCall) Return(arg0 error) *MockPoolCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPoolCloseCall) Do(f func() error) *MockPoolCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoolCloseCall) DoAndReturn(f func() error) *MockPoolCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExecContext mocks base method.
func (m *MockPool) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockPoolMockRecorder) ExecContext(ctx, query any, args ...any) *MockPoolExecContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockPool)(nil).ExecContext), varargs...)
	return &MockPoolExecContextCall{Call: call}
}

// MockPoolExecContextCall wrap *gomock.Call
type MockPoolExecContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoolExecContextCall) Return(arg0 sql.Result, arg1 error) *MockPoolExecContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPoolExecContextCall) Do(f func(context.Context, string, ...any) (sql.Result, error)) *MockPoolExecContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoolExecContextCall) DoAndReturn(f func(context.Context, string, ...any) (sql.Result, error)) *MockPoolExecContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PingContext mocks base method.
func (m *MockPool) PingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockPoolMockRecorder) PingContext(ctx any) *MockPoolPingContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockPool)(nil).PingContext), ctx)
	return &MockPoolPingContextCall{Call: call}
}

// MockPoolPingContextCall wrap *gomock.Call
type MockPoolPingContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoolPingContextCall) Return(arg0 error) *MockPoolPingContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPoolPingContextCall) Do(f func(context.Context) error) *MockPoolPingContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoolPingContextCall) DoAndReturn(f func(context.Context) error) *MockPoolPingContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryRowContext mocks base method.
func (m *MockPool) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockPoolMockRecorder) QueryRowContext(ctx, query any, args ...any) *MockPoolQueryRowContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockPool)(nil).QueryRowContext), varargs...)
	return &MockPoolQueryRowContextCall{Call: call}
}

// MockPoolQueryRowContextCall wrap *gomock.Call
type MockPoolQueryRowContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoolQueryRowContextCall) Return(arg0 *sql.Row) *MockPoolQueryRowContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPoolQueryRowContextCall) Do(f func(context.Context, string, ...any) *sql.Row) *MockPoolQueryRowContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoolQueryRowContextCall) DoAndReturn(f func(context.Context, string, ...any) *sql.Row) *MockPoolQueryRowContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
	isgomock struct{}
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// OpenPing mocks base method.
func (m *MockConnector) OpenPing(ctx context.Context, databaseURL string) (postgres.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenPing", ctx, databaseURL)
	ret0, _ := ret[0].(postgres.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenPing indicates an expected call of OpenPing.
func (mr *MockConnectorMockRecorder) OpenPing(ctx, databaseURL any) *MockConnectorOpenPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenPing", reflect.TypeOf((*MockConnector)(nil).OpenPing), ctx, databaseURL)
	return &MockConnectorOpenPingCall{Call: call}
}

// MockConnectorOpenPingCall wrap *gomock.Call
type MockConnectorOpenPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectorOpenPingCall) Return(arg0 postgres.Pool, arg1 error) *MockConnectorOpenPingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectorOpenPingCall) Do(f func(context.Context, string) (postgres.Pool, error)) *MockConnectorOpenPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectorOpenPingCall) DoAndReturn(f func(context.Context, string) (postgres.Pool, error)) *MockConnectorOpenPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
