package auth_test

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/prbllm/goph-keeper/internal/server/auth"
	"github.com/prbllm/goph-keeper/internal/server/auth/mocks"
	"go.uber.org/mock/gomock"
)

func fixedClock() auth.Clock {
	t0 := time.Date(2025, 3, 1, 12, 0, 0, 0, time.UTC)
	return func() time.Time { return t0 }
}

func newTestService(ctrl *gomock.Controller, now auth.Clock) (
	*auth.Service,
	*mocks.MockUserRepository,
	*mocks.MockSessionRepository,
	*mocks.MockAuthTx,
	*mocks.MockPasswordHasher,
	*mocks.MockTokenIssuer,
) {
	if now == nil {
		now = fixedClock()
	}
	users := mocks.NewMockUserRepository(ctrl)
	sessions := mocks.NewMockSessionRepository(ctrl)
	authTx := mocks.NewMockAuthTx(ctrl)
	hasher := mocks.NewMockPasswordHasher(ctrl)
	issuer := mocks.NewMockTokenIssuer(ctrl)
	svc := auth.NewService(
		users, sessions, authTx, hasher, issuer, now,
		time.Minute, time.Hour,
		65536, 104857600, 8388608,
	)
	return svc, users, sessions, authTx, hasher, issuer
}

func TestService_Register_invalidArgument(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, _, _, _ := newTestService(ctrl, nil)

	_, err := svc.Register(ctx, auth.RegisterInput{Login: "", Password: "x"})
	if !errors.Is(err, auth.ErrInvalidArgument) {
		t.Fatalf("Register: %v, want ErrInvalidArgument", err)
	}
	_, err = svc.Register(ctx, auth.RegisterInput{Login: "a", Password: ""})
	if !errors.Is(err, auth.ErrInvalidArgument) {
		t.Fatalf("Register: %v, want ErrInvalidArgument", err)
	}
}

func TestService_Register_hashError(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, _, hasher, _ := newTestService(ctrl, nil)
	want := errors.New("hash failed")
	hasher.EXPECT().Hash("pw").Return(nil, want)

	_, err := svc.Register(ctx, auth.RegisterInput{Login: "u", Password: "pw"})
	if !errors.Is(err, want) {
		t.Fatalf("Register: %v, want %v", err, want)
	}
}

func TestService_Register_authTxError(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, authTx, hasher, _ := newTestService(ctrl, nil)
	hasher.EXPECT().Hash("pw").Return([]byte("h"), nil)
	want := auth.ErrAlreadyExists
	authTx.EXPECT().RegisterWithSession(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(want)

	_, err := svc.Register(ctx, auth.RegisterInput{Login: "u", Password: "pw"})
	if !errors.Is(err, want) {
		t.Fatalf("Register: %v, want %v", err, want)
	}
}

func TestService_Register_tokenError(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, authTx, hasher, issuer := newTestService(ctrl, nil)
	hasher.EXPECT().Hash("pw").Return([]byte("h"), nil)
	authTx.EXPECT().RegisterWithSession(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
	want := errors.New("sign failed")
	issuer.EXPECT().IssueAccessToken(gomock.Any(), gomock.Any()).Return("", want)

	_, err := svc.Register(ctx, auth.RegisterInput{Login: "u", Password: "pw"})
	if !errors.Is(err, want) {
		t.Fatalf("Register: %v, want %v", err, want)
	}
}

func TestService_Register_success(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, authTx, hasher, issuer := newTestService(ctrl, nil)
	hasher.EXPECT().Hash("pw").Return([]byte("h"), nil)
	authTx.EXPECT().RegisterWithSession(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
	issuer.EXPECT().IssueAccessToken(gomock.Any(), gomock.Any()).DoAndReturn(
		func(c auth.AccessTokenClaims, ttl time.Duration) (string, error) {
			if c.UserID == "" || c.DeviceID == "" {
				t.Error("expected non-empty UserID and DeviceID in claims")
			}
			if ttl != time.Minute {
				t.Errorf("ttl %v, want 1m", ttl)
			}
			return "access-jwt", nil
		})

	out, err := svc.Register(ctx, auth.RegisterInput{Login: "u", Password: "pw"})
	if err != nil {
		t.Fatal(err)
	}
	if out.Login != "u" || out.UserID == "" || out.DeviceID == "" {
		t.Fatalf("unexpected output: %+v", out)
	}
	if out.AccessToken != "access-jwt" || out.RefreshToken == "" {
		t.Fatalf("tokens: access=%q refresh empty=%v", out.AccessToken, out.RefreshToken == "")
	}
}

func TestService_Register_success_emptyDeviceID_autogenerated(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, authTx, hasher, issuer := newTestService(ctrl, nil)
	hasher.EXPECT().Hash("pw").Return([]byte("h"), nil)
	authTx.EXPECT().RegisterWithSession(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
	issuer.EXPECT().IssueAccessToken(gomock.Any(), gomock.Any()).Return("access-jwt", nil)

	out, err := svc.Register(ctx, auth.RegisterInput{Login: "u", Password: "pw", DeviceID: ""})
	if err != nil {
		t.Fatal(err)
	}
	if out.DeviceID == "" {
		t.Fatal("expected autogenerated device id")
	}
}

func TestService_Login_invalidArgument(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, _, _, _ := newTestService(ctrl, nil)
	_, err := svc.Login(ctx, auth.LoginInput{Login: "", Password: "x"})
	if !errors.Is(err, auth.ErrInvalidArgument) {
		t.Fatalf("Login: %v", err)
	}
}

func TestService_Login_userLookupError(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, users, _, _, _, _ := newTestService(ctrl, nil)
	want := errors.New("db down")
	users.EXPECT().GetByLogin(gomock.Any(), "u").Return(nil, want)

	_, err := svc.Login(ctx, auth.LoginInput{Login: "u", Password: "pw"})
	if !errors.Is(err, want) {
		t.Fatalf("Login: %v, want %v", err, want)
	}
}

func TestService_Login_wrongPassword(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, users, _, _, hasher, _ := newTestService(ctrl, nil)
	users.EXPECT().GetByLogin(gomock.Any(), "u").Return(&auth.User{UserID: "id", PasswordHash: []byte("x")}, nil)
	hasher.EXPECT().Compare([]byte("x"), "bad").Return(errors.New("mismatch"))

	_, err := svc.Login(ctx, auth.LoginInput{Login: "u", Password: "bad"})
	if !errors.Is(err, auth.ErrUnauthorized) {
		t.Fatalf("Login: %v, want ErrUnauthorized", err)
	}
}

func TestService_Login_success(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, users, _, authTx, hasher, issuer := newTestService(ctrl, nil)
	u := &auth.User{
		UserID:                 "user-1",
		Login:                  "alice",
		PasswordHash:           []byte("hash"),
		PasswordSalt:           []byte("salt"),
		KDFAlgorithm:           "argon2id",
		KDFMemoryKiB:           1,
		KDFIterations:          2,
		KDFParallelism:         3,
		KDFKeyLength:           32,
		EncryptedVaultKey:      []byte("k"),
		EncryptedVaultKeyNonce: []byte("n"),
	}
	users.EXPECT().GetByLogin(gomock.Any(), "alice").Return(u, nil)
	hasher.EXPECT().Compare(u.PasswordHash, "pw").Return(nil)
	authTx.EXPECT().LoginWithDeviceAndSession(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
	issuer.EXPECT().IssueAccessToken(gomock.Any(), gomock.Any()).Return("jwt-access", nil)

	out, err := svc.Login(ctx, auth.LoginInput{Login: "alice", Password: "pw", DeviceID: "dev-1"})
	if err != nil {
		t.Fatal(err)
	}
	if out.UserID != "user-1" || out.Login != "alice" || out.DeviceID != "dev-1" {
		t.Fatalf("unexpected %+v", out)
	}
	if out.AccessToken != "jwt-access" || out.RefreshToken == "" {
		t.Fatal("missing tokens")
	}
	if string(out.PasswordSalt) != "salt" || string(out.EncryptedVaultKey) != "k" {
		t.Fatal("vault metadata not propagated")
	}
}

func TestService_Login_success_emptyDeviceID_autogenerated(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, users, _, authTx, hasher, issuer := newTestService(ctrl, nil)
	u := &auth.User{
		UserID:       "user-1",
		Login:        "alice",
		PasswordHash: []byte("hash"),
	}
	users.EXPECT().GetByLogin(gomock.Any(), "alice").Return(u, nil)
	hasher.EXPECT().Compare(u.PasswordHash, "pw").Return(nil)
	authTx.EXPECT().LoginWithDeviceAndSession(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
	issuer.EXPECT().IssueAccessToken(gomock.Any(), gomock.Any()).Return("jwt-access", nil)

	out, err := svc.Login(ctx, auth.LoginInput{Login: "alice", Password: "pw", DeviceID: ""})
	if err != nil {
		t.Fatal(err)
	}
	if out.DeviceID == "" {
		t.Fatal("expected autogenerated device id")
	}
}

func TestService_Refresh_invalidArgument(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, _, _, _ := newTestService(ctrl, nil)
	_, err := svc.Refresh(ctx, auth.RefreshInput{RefreshToken: "", DeviceID: "d"})
	if !errors.Is(err, auth.ErrInvalidArgument) {
		t.Fatalf("Refresh: %v", err)
	}
}

func TestService_Refresh_rotateError(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, sessions, _, _, _ := newTestService(ctrl, nil)
	sessions.EXPECT().RotateRefresh(gomock.Any(), gomock.Any(), "dev", gomock.Any(), gomock.Any()).Return(auth.ErrUnauthorized)

	_, err := svc.Refresh(ctx, auth.RefreshInput{RefreshToken: "rt", DeviceID: "dev"})
	if !errors.Is(err, auth.ErrUnauthorized) {
		t.Fatalf("Refresh: %v", err)
	}
}

func TestService_Refresh_wrongDeviceID(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, sessions, _, _, _ := newTestService(ctrl, nil)
	sessions.EXPECT().RotateRefresh(gomock.Any(), gomock.Any(), "wrong-device", gomock.Any(), gomock.Any()).Return(auth.ErrUnauthorized)

	_, err := svc.Refresh(ctx, auth.RefreshInput{RefreshToken: "rt", DeviceID: "wrong-device"})
	if !errors.Is(err, auth.ErrUnauthorized) {
		t.Fatalf("Refresh: %v, want ErrUnauthorized", err)
	}
}

func TestService_Refresh_tokenIssueError(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, sessions, _, _, issuer := newTestService(ctrl, nil)
	sessions.EXPECT().RotateRefresh(gomock.Any(), gomock.Any(), "dev", gomock.Any(), gomock.Any()).
		DoAndReturn(func(_ context.Context, _ []byte, _ string, _ time.Time, newS *auth.Session) error {
			newS.UserID = "u1"
			newS.DeviceID = "dev"
			return nil
		})
	want := errors.New("sign")
	issuer.EXPECT().IssueAccessToken(gomock.Any(), gomock.Any()).Return("", want)

	_, err := svc.Refresh(ctx, auth.RefreshInput{RefreshToken: "plain-refresh", DeviceID: "dev"})
	if !errors.Is(err, want) {
		t.Fatalf("Refresh: %v", err)
	}
}

func TestService_Refresh_success(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, sessions, _, _, issuer := newTestService(ctrl, nil)
	sessions.EXPECT().RotateRefresh(gomock.Any(), gomock.Any(), "dev", gomock.Any(), gomock.Any()).
		DoAndReturn(func(_ context.Context, _ []byte, _ string, _ time.Time, newS *auth.Session) error {
			newS.UserID = "u1"
			newS.DeviceID = "dev"
			return nil
		})
	issuer.EXPECT().IssueAccessToken(auth.AccessTokenClaims{UserID: "u1", DeviceID: "dev"}, time.Minute).
		Return("new-access", nil)

	out, err := svc.Refresh(ctx, auth.RefreshInput{RefreshToken: "plain-refresh", DeviceID: "dev"})
	if err != nil {
		t.Fatal(err)
	}
	if out.AccessToken != "new-access" || out.RefreshToken == "" {
		t.Fatalf("unexpected %+v", out)
	}
}

func TestService_Logout_invalidArgument(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, _, _, _, _ := newTestService(ctrl, nil)
	if err := svc.Logout(ctx, "  "); !errors.Is(err, auth.ErrInvalidArgument) {
		t.Fatalf("Logout: %v", err)
	}
}

func TestService_Logout_revokeUnauthorizedIgnored(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, sessions, _, _, _ := newTestService(ctrl, nil)
	sessions.EXPECT().RevokeByHash(gomock.Any(), gomock.Any()).Return(auth.ErrUnauthorized)

	if err := svc.Logout(ctx, "any-plain-token"); err != nil {
		t.Fatalf("Logout: %v, want nil", err)
	}
}

func TestService_Logout_revokeError(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, sessions, _, _, _ := newTestService(ctrl, nil)
	want := errors.New("db")
	sessions.EXPECT().RevokeByHash(gomock.Any(), gomock.Any()).Return(want)

	if err := svc.Logout(ctx, "token"); !errors.Is(err, want) {
		t.Fatalf("Logout: %v, want %v", err, want)
	}
}

func TestService_Logout_success(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ctrl := gomock.NewController(t)
	svc, _, sessions, _, _, _ := newTestService(ctrl, nil)
	sessions.EXPECT().RevokeByHash(gomock.Any(), gomock.Any()).Return(nil)

	if err := svc.Logout(ctx, "plain-refresh"); err != nil {
		t.Fatal(err)
	}
}
