// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/api/proto/gophkeeper/v1 (interfaces: BlobServiceClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gophkeeperv1 "github.com/prbllm/goph-keeper/api/proto/gophkeeper/v1"
	grpc "google.golang.org/grpc"
)

// MockBlobServiceClient is a mock of BlobServiceClient interface.
type MockBlobServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlobServiceClientMockRecorder
}

// MockBlobServiceClientMockRecorder is the mock recorder for MockBlobServiceClient.
type MockBlobServiceClientMockRecorder struct {
	mock *MockBlobServiceClient
}

// NewMockBlobServiceClient creates a new mock instance.
func NewMockBlobServiceClient(ctrl *gomock.Controller) *MockBlobServiceClient {
	mock := &MockBlobServiceClient{ctrl: ctrl}
	mock.recorder = &MockBlobServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobServiceClient) EXPECT() *MockBlobServiceClientMockRecorder {
	return m.recorder
}

// CommitBlobUpload mocks base method.
func (m *MockBlobServiceClient) CommitBlobUpload(arg0 context.Context, arg1 *gophkeeperv1.CommitBlobUploadRequest, arg2 ...grpc.CallOption) (*gophkeeperv1.CommitBlobUploadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitBlobUpload", varargs...)
	ret0, _ := ret[0].(*gophkeeperv1.CommitBlobUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitBlobUpload indicates an expected call of CommitBlobUpload.
func (mr *MockBlobServiceClientMockRecorder) CommitBlobUpload(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitBlobUpload", reflect.TypeOf((*MockBlobServiceClient)(nil).CommitBlobUpload), varargs...)
}

// DownloadBlob mocks base method.
func (m *MockBlobServiceClient) DownloadBlob(arg0 context.Context, arg1 *gophkeeperv1.DownloadBlobRequest, arg2 ...grpc.CallOption) (grpc.ServerStreamingClient[gophkeeperv1.DownloadBlobResponse], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DownloadBlob", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[gophkeeperv1.DownloadBlobResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadBlob indicates an expected call of DownloadBlob.
func (mr *MockBlobServiceClientMockRecorder) DownloadBlob(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadBlob", reflect.TypeOf((*MockBlobServiceClient)(nil).DownloadBlob), varargs...)
}

// StartBlobUpload mocks base method.
func (m *MockBlobServiceClient) StartBlobUpload(arg0 context.Context, arg1 *gophkeeperv1.StartBlobUploadRequest, arg2 ...grpc.CallOption) (*gophkeeperv1.StartBlobUploadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartBlobUpload", varargs...)
	ret0, _ := ret[0].(*gophkeeperv1.StartBlobUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBlobUpload indicates an expected call of StartBlobUpload.
func (mr *MockBlobServiceClientMockRecorder) StartBlobUpload(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBlobUpload", reflect.TypeOf((*MockBlobServiceClient)(nil).StartBlobUpload), varargs...)
}

// UploadBlob mocks base method.
func (m *MockBlobServiceClient) UploadBlob(arg0 context.Context, arg1 ...grpc.CallOption) (grpc.ClientStreamingClient[gophkeeperv1.UploadBlobRequest, gophkeeperv1.UploadBlobResponse], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadBlob", varargs...)
	ret0, _ := ret[0].(grpc.ClientStreamingClient[gophkeeperv1.UploadBlobRequest, gophkeeperv1.UploadBlobResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadBlob indicates an expected call of UploadBlob.
func (mr *MockBlobServiceClientMockRecorder) UploadBlob(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadBlob", reflect.TypeOf((*MockBlobServiceClient)(nil).UploadBlob), varargs...)
}
