// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/api/proto/gophkeeper/v1 (interfaces: BlobService_DownloadBlobClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gophkeeperv1 "github.com/prbllm/goph-keeper/api/proto/gophkeeper/v1"
	metadata "google.golang.org/grpc/metadata"
)

// MockBlobService_DownloadBlobClient is a mock of BlobService_DownloadBlobClient interface.
type MockBlobService_DownloadBlobClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlobService_DownloadBlobClientMockRecorder
}

// MockBlobService_DownloadBlobClientMockRecorder is the mock recorder for MockBlobService_DownloadBlobClient.
type MockBlobService_DownloadBlobClientMockRecorder struct {
	mock *MockBlobService_DownloadBlobClient
}

// NewMockBlobService_DownloadBlobClient creates a new mock instance.
func NewMockBlobService_DownloadBlobClient(ctrl *gomock.Controller) *MockBlobService_DownloadBlobClient {
	mock := &MockBlobService_DownloadBlobClient{ctrl: ctrl}
	mock.recorder = &MockBlobService_DownloadBlobClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobService_DownloadBlobClient) EXPECT() *MockBlobService_DownloadBlobClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockBlobService_DownloadBlobClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockBlobService_DownloadBlobClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockBlobService_DownloadBlobClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockBlobService_DownloadBlobClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockBlobService_DownloadBlobClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBlobService_DownloadBlobClient)(nil).Context))
}

// Header mocks base method.
func (m *MockBlobService_DownloadBlobClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockBlobService_DownloadBlobClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockBlobService_DownloadBlobClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockBlobService_DownloadBlobClient) Recv() (*gophkeeperv1.DownloadBlobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*gophkeeperv1.DownloadBlobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockBlobService_DownloadBlobClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockBlobService_DownloadBlobClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockBlobService_DownloadBlobClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockBlobService_DownloadBlobClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockBlobService_DownloadBlobClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockBlobService_DownloadBlobClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockBlobService_DownloadBlobClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockBlobService_DownloadBlobClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockBlobService_DownloadBlobClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockBlobService_DownloadBlobClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockBlobService_DownloadBlobClient)(nil).Trailer))
}
