// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prbllm/goph-keeper/api/proto/gophkeeper/v1 (interfaces: BlobService_UploadBlobClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gophkeeperv1 "github.com/prbllm/goph-keeper/api/proto/gophkeeper/v1"
	metadata "google.golang.org/grpc/metadata"
)

// MockBlobService_UploadBlobClient is a mock of BlobService_UploadBlobClient interface.
type MockBlobService_UploadBlobClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlobService_UploadBlobClientMockRecorder
}

// MockBlobService_UploadBlobClientMockRecorder is the mock recorder for MockBlobService_UploadBlobClient.
type MockBlobService_UploadBlobClientMockRecorder struct {
	mock *MockBlobService_UploadBlobClient
}

// NewMockBlobService_UploadBlobClient creates a new mock instance.
func NewMockBlobService_UploadBlobClient(ctrl *gomock.Controller) *MockBlobService_UploadBlobClient {
	mock := &MockBlobService_UploadBlobClient{ctrl: ctrl}
	mock.recorder = &MockBlobService_UploadBlobClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobService_UploadBlobClient) EXPECT() *MockBlobService_UploadBlobClientMockRecorder {
	return m.recorder
}

// CloseAndRecv mocks base method.
func (m *MockBlobService_UploadBlobClient) CloseAndRecv() (*gophkeeperv1.UploadBlobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAndRecv")
	ret0, _ := ret[0].(*gophkeeperv1.UploadBlobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockBlobService_UploadBlobClientMockRecorder) CloseAndRecv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAndRecv", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).CloseAndRecv))
}

// CloseSend mocks base method.
func (m *MockBlobService_UploadBlobClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockBlobService_UploadBlobClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockBlobService_UploadBlobClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockBlobService_UploadBlobClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).Context))
}

// Header mocks base method.
func (m *MockBlobService_UploadBlobClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockBlobService_UploadBlobClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).Header))
}

// RecvMsg mocks base method.
func (m *MockBlobService_UploadBlobClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockBlobService_UploadBlobClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockBlobService_UploadBlobClient) Send(arg0 *gophkeeperv1.UploadBlobRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBlobService_UploadBlobClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m *MockBlobService_UploadBlobClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockBlobService_UploadBlobClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockBlobService_UploadBlobClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockBlobService_UploadBlobClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockBlobService_UploadBlobClient)(nil).Trailer))
}
