name: Manual Test Release

on:
  workflow_dispatch: # Позволяет запускать сборку кнопкой из GitHub Actions

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 нужен для корректной работы инструментов сборки
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.7' # Используем стабильную версию
          cache: true        # Включаем кэширование зависимостей

      - name: Build Test Binaries
        # Собираем бинарники для проверки, что код компилируется под разные ОС
        # Флаг -v выведет подробности сборки
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X 'github.com/prbllm/goph-keeper/pkg/version.Version=v1.0.1' -X 'github.com/prbllm/goph-keeper/pkg/version.BuildDate=$(date +'%Y/%m/%d %H:%M:%S')'" -v ./cmd/client/ -o ./bin/gophkeeper_client-linux-amd64
          GOOS=windows GOARCH=amd64 go build -ldflags "-X 'github.com/prbllm/goph-keeper/pkg/version.Version=v1.0.1' -X 'github.com/prbllm/goph-keeper/pkg/version.BuildDate=$(date +'%Y/%m/%d %H:%M:%S')'" -v ./cmd/client/ -o ./bin/gophkeeper_client-windows-amd64.exe
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'github.com/prbllm/goph-keeper/pkg/version.Version=v1.0.1' -X 'github.com/prbllm/goph-keeper/pkg/version.BuildDate=$(date +'%Y/%m/%d %H:%M:%S')'" -v ./cmd/client/ -o ./bin/gophkeeper_client-macos-arm64

      - name: Upload Artifacts
        # Сохраняем собранные файлы в GitHub Actions (их можно будет скачать)
        uses: actions/upload-artifact@v4
        with:
          name: test-binaries-${{ github.sha }}
          path: ./bin/
          retention-days: 1 # Файлы удалятся через день, чтобы не занимать место
